export const ESTADOS_MEXICO = [
  { nombre: 'Aguascalientes', ciudades: ['Aguascalientes', 'Asientos', 'Calvillo', 'Cosío', 'Jesús María', 'Pabellón de Arteaga', 'Rincón de Romos', 'San José de Gracia', 'Tepezalá', 'El Llano', 'San Francisco de los Romo'] },
  { nombre: 'Baja California', ciudades: ['Mexicali', 'Tijuana', 'Tecate', 'Playas de Rosarito', 'Ensenada'] },
  { nombre: 'Baja California Sur', ciudades: ['La Paz', 'Los Cabos', 'Comondú', 'Loreto', 'Mulegé'] },
  { nombre: 'Campeche', ciudades: ['Campeche', 'Calkiní', 'Carmen', 'Champotón', 'Escárcega', 'Hecelchakán', 'Hopelchén', 'Palizada', 'Tenabo', 'Calakmul'] },
  { nombre: 'Chiapas', ciudades: ['Tuxtla Gutiérrez', 'Tapachula', 'San Cristóbal de las Casas', 'Comitán', 'Ocosingo', 'Palenque', 'San Fernando', 'Tonala', 'Villaflores', 'Yajalón'] },
  { nombre: 'Chihuahua', ciudades: ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Cuauhtémoc', 'Parral', 'Nuevo Casas Grandes', 'Ojinaga', 'Camargo'] },
  { nombre: 'Ciudad de México', ciudades: ['Álvaro Obregón', 'Azcapotzalco', 'Benito Juárez', 'Coyoacán', 'Cuajimalpa', 'Cuauhtémoc', 'Gustavo A. Madero', 'Iztacalco', 'Iztapalapa', 'La Magdalena Contreras', 'Miguel Hidalgo', 'Milpa Alta', 'Tláhuac', 'Tlalpan', 'Venustiano Carranza', 'Xochimilco'] },
  { nombre: 'Coahuila', ciudades: ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras', 'Acuña', 'San Pedro', 'Sabinas'] },
  { nombre: 'Colima', ciudades: ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez', 'Armería', 'Comala', 'Minatitlán', 'Coquimatlán'] },
  { nombre: 'Durango', ciudades: ['Durango', 'Gómez Palacio', 'Lerdo', 'Canatlán', 'Nuevo Ideal', 'Poanas', 'San Dimas'] },
  { nombre: 'Guanajuato', ciudades: ['Guanajuato', 'Irapuato', 'León', 'Celaya', 'San Miguel de Allende', 'Salamanca', 'San Francisco del Rincón', 'Silao', 'Pénjamo', 'Valle de Santiago'] },
  { nombre: 'Guerrero', ciudades: ['Acapulco', 'Chilpancingo', 'Iguala', 'Zihuatanejo', 'Chilapa', 'Taxco', 'Ometepec'] },
  { nombre: 'Hidalgo', ciudades: ['Pachuca', 'Tulancingo', 'Tula', 'Ixmiquilpan', 'Actopan', 'Tepeji del Río', 'Zimapán'] },
  { nombre: 'Jalisco', ciudades: ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonala', 'Puerto Vallarta', 'Ocotlán', 'Tepatitlán', 'Lagos de Moreno', 'Tequila'] },
  { nombre: 'México', ciudades: ['Toluca', 'Ecatepec', 'Nezahualcóyotl', 'Naucalpan', 'Tlalnepantla', 'Chimalhuacán', 'Ixtapaluca'] },
  { nombre: 'Michoacán', ciudades: ['Morelia', 'Uruapan', 'Lázaro Cárdenas', 'Zamora', 'Pátzcuaro'] },
  { nombre: 'Morelos', ciudades: ['Cuernavaca', 'Jiutepec', 'Temixco', 'Cuautla', 'Yautepec'] },
  { nombre: 'Nayarit', ciudades: ['Tepic', 'Bahía de Banderas', 'Compostela', 'Xalisco', 'Ixtlán del Río'] },
  { nombre: 'Nuevo León', ciudades: ['Monterrey', 'San Nicolás', 'Apodaca', 'Guadalupe', 'Santa Catarina', 'San Pedro Garza García'] },
  { nombre: 'Oaxaca', ciudades: ['Oaxaca', 'Salina Cruz', 'Juchitán', 'Tehuantepec', 'Santa Cruz Xoxocotlán'] },
  { nombre: 'Puebla', ciudades: ['Puebla', 'Tehuacán', 'Atlixco', 'San Martín Texmelucan', 'Cholula'] },
  { nombre: 'Querétaro', ciudades: ['Querétaro', 'San Juan del Río', 'El Marqués', 'Tequisquiapan'] },
  { nombre: 'Quintana Roo', ciudades: ['Cancún', 'Chetumal', 'Playa del Carmen', 'Cozumel', 'Tulum'] },
  { nombre: 'San Luis Potosí', ciudades: ['San Luis Potosí', 'Ciudad Valles', 'Matehuala', 'Soledad', 'Rioverde'] },
  { nombre: 'Sinaloa', ciudades: ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guamúchil', 'Guasave'] },
  { nombre: 'Sonora', ciudades: ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'Navojoa', 'Guaymas'] },
  { nombre: 'Tabasco', ciudades: ['Villahermosa', 'Cárdenas', 'Comalcalco', 'Macuspana', 'Paraíso'] },
  { nombre: 'Tamaulipas', ciudades: ['Tampico', 'Reynosa', 'Matamoros', 'Ciudad Victoria', 'Nuevo Laredo'] },
  { nombre: 'Tlaxcala', ciudades: ['Tlaxcala', 'Apizaco', 'Chiautempan', 'Huamantla', 'Papalotla'] },
  { nombre: 'Veracruz', ciudades: ['Veracruz', 'Xalapa', 'Coatzacoalcos', 'Orizaba', 'Poza Rica'] },
  { nombre: 'Yucatán', ciudades: ['Mérida', 'Valladolid', 'Tizimín', 'Progreso', 'Ticul'] },
  { nombre: 'Zacatecas', ciudades: ['Zacatecas', 'Fresnillo', 'Guadalupe', 'Jerez', 'Jalpa'] }
];
